COLOR_FACT = 0
COLOR_EVIDENCE = 1
COLOR_DISAGREEMENT = 2
COLOR_VERIFY = 3
COLOR_SUMMARY = 4
COLOR_CONSENSUS = 5
COLOR_TOOL_CALL = 6
COLOR_MEMORY = 7
COLOR_IMAGE = 8
COLOR_TABLE = 9
COLOR_REROUTE = 10
COLOR_THROTTLE = 11
COLOR_AMPLIFY = 12
COLOR_COOLING = 13
COLOR_WAVELET = 14
COLOR_ARBITER = 15
COLOR_ERROR = 16
COLOR_LATENCY = 17
COLOR_CONFIDENCE = 18
COLOR_CLUSTER = 19
COLOR_PRIORITY = 20
COLOR_BROADCAST = 21
COLOR_FINAL = 22
COLOR_RESERVED = 23

COLOR_NAMES = {
    COLOR_FACT: "FACT",
    COLOR_EVIDENCE: "EVIDENCE",
    COLOR_DISAGREEMENT: "DISAGREEMENT",
    COLOR_VERIFY: "VERIFY",
    COLOR_SUMMARY: "SUMMARY",
    COLOR_CONSENSUS: "CONSENSUS",
    COLOR_TOOL_CALL: "TOOL_CALL",
    COLOR_MEMORY: "MEMORY",
    COLOR_IMAGE: "IMAGE",
    COLOR_TABLE: "TABLE",
    COLOR_REROUTE: "REROUTE",
    COLOR_THROTTLE: "THROTTLE",
    COLOR_AMPLIFY: "AMPLIFY",
    COLOR_COOLING: "COOLING",
    COLOR_WAVELET: "WAVELET",
    COLOR_ARBITER: "ARBITER",
    COLOR_ERROR: "ERROR",
    COLOR_LATENCY: "LATENCY",
    COLOR_CONFIDENCE: "CONFIDENCE",
    COLOR_CLUSTER: "CLUSTER",
    COLOR_PRIORITY: "PRIORITY",
    COLOR_BROADCAST: "BROADCAST",
    COLOR_FINAL: "FINAL",
    COLOR_RESERVED: "RESERVED"
}
