WSE_NAME = "WSE-3"
WSE_PROCESS_NM = 5
WSE_AREA_MM2 = 46225
WSE_TRANSISTORS = 4_000_000_000_000
WSE_CORES = 900_000
WSE_DIES = 84
CORES_PER_DIE = 10_000

MEMORY_PER_CORE_KB = 48
CORE_AREA_UM2 = 38_000

WSE_MEMORY_BANDWIDTH_PB_PER_S = 21
WSE_FABRIC_BANDWIDTH_PB_PER_S = 214

FABRIC_TOPOLOGY = "2D mesh"
ROUTER_PORTS = 5
ROUTER_DIRECTIONS = ["N", "S", "E", "W", "CORE"]

PACKET_BITS = 32
PACKET_DATA_BITS = 16
PACKET_CONTROL_BITS = 16

ROUTING_MODE = "static"
COLORS_PER_CORE = 24

FABRIC_LATENCY_DESCRIPTION = "single clock cycle between neighboring nodes"
FLOW_CONTROL = "lossless low-buffering"
BROADCAST_MULTICAST_SUPPORTED = True

MICROTHREADS_PER_CORE = 8

# Scaled simulation mesh parameters
SELECTED_AGENTS = 15_000
SIM_MESH_W = 125
SIM_MESH_H = 120
SIM_MESH_NODES = SIM_MESH_W * SIM_MESH_H
